name: Issue Template Config
description: Controls how issue templates appear
blank_issues_enabled: false
contact_links:

name: Discussions
url: https://github.com/jacob1-x/F-Static-CDN-deliver/discussions
about: Ask questions or talk about ideas here
